### ISSUE TITLE
Reference to non-existent field 'Size_x_Chi'.

### ISSUE THREAD

**Issue by aghaeifar** [RainerBoegle/deltaB0_CalcTool#1]
Hi Rainer

I got an error when running one of your tutorial scripts: '_Compare_Sphere_Calc_deltaB_to_analyticSolution_'

Here is the error message:

```
Reference to non-existent field 'Size_x_Chi'.
Error in pad_Chi_2_VOI (line 123)
ParameterStruct.Size_x_VOI = ParameterStruct.Size_x_Chi * ISOPadFactor;
```

Seems the field "_Size_x_Chi_" doesn't exist in the ParameterStruct from the beginning. Where should I fill this field in the example scripts? 
Are _Size_x_Chi_ and _Size_x_ same? How about _FOV_x_Chi_ and _FOV_x_ ?

Thanks,
Ali

**Comment by RainerBoegle** [comment]
Hi Ali,

1.sorry for the delay
2.sorry for the issue, it turns out that this script was for a previous version... Well, that's embarrassing. ;)
3.it's been a long time ago and I am still trying to understand my own code again... Also embarrassing ;)
4.I almost feel like I should rewrite the whole thing, now I could probably do it better.

However, I don't have the time to do a complete overhaul, therefore, I fixed only this one script.
Try it out, it should produce figures with reasonable results now.
Please report further problems, I will fix them if I find the time.
The calculation tools should work though, it seems that I didn't adjust the demos, therefore the rest should be fine.
